#!/usr/bin/env bash
# Script that install nginx and start that services.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
service nginx start
