#!/usr/bin/env bash
# Script that install nginx and start that services.
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
