#!/usr/bin/env bash
# Script that install nginx and start that services.
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i '/^\tserver_name localhost;/ a\\n\tlocation \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\}\n' $file
sudo service nginx restart
