#!/usr/bin/env bash
# Configures Ubuntu server with a custom HTTP header.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\tserver_name localhost;/ a\\tadd_header X-Served-By '"$HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
