#!/usr/bin/env bash
# Configures Ubuntu server with a custom HTTP header.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Load Balancer' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
