#!/usr/bin/env bash
# Install load balance
sudo apt-get -y update
sudo apt install -y haproxy=1.8.\*
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend http_front
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        mode http
        balance roundrobin
        server web-01 34.138.9.75:80 check
        server web-02 54.86.211.56:80 check
EOF

service haproxy start
