#!/usr/bin/env bash
# Bash script display "Holberton School" 10 times
# But for the 9th iteration, displays Hi

i=0

while [ $i -lt 10 ];
do
echo "Holberton School"
if [ $i -ge 8 ];
then
echo "Hi"
fi
((i++))
done
