#!/usr/bin/env bash
# Bash script loops 1 to 10
# Display bad luck for 4 loop
# Display good luck for 8 loop
# Display Holberton school for other

i=0

while [ $i -lt 10 ];
do
if [ $i -eq 3 ];
then
echo "bad luck"
elif [ $i -eq 7 ];
then
echo "good luck"
else
echo "Holberton School"
fi
((i++))
done
