#!/usr/bin/env bash
# Bash script 1 to 20
# Display 4 china.. 9 japan.. 17 italy..

i=1
while [ $i -le 20 ];
do
echo "$i"
case "$i" in
4)
echo "bad luck from China";;
9)
echo "bad luck from Japan";;
17)
echo "bad luck from Italy";;
esac
((i++))
done
