#!/usr/bin/env bash
# Bash script display time 12 hours and 59 minutes.

hours=0
minutes=1

while [ $hours -le 12 ];
do
echo "Hour: $hours"
fi
echo "$minutes"
if [ $minutes -eq 59 ];
then
(($hours++))
else
(($minutes++))
fi
done
