#!/usr/bin/env bash
# Script display holbertonschool file

i="holbertonschool"
if [ -e $i ]
then
echo "holbertonschool file exits"
if [ -s $i ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi
if [ -f $i ]
then
echo "holbertonschool is a regular file"
fi
else
echo "holbertonschool file does not exist"
fi
